"""empty message

Revision ID: 08b37f302f66
Revises: 29de48ef05f1
Create Date: 2018-04-11 14:02:28.576850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b37f302f66'
down_revision = '29de48ef05f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_browser', sa.Column('ua', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_browser', 'ua')
    # ### end Alembic commands ###
