"""empty message

Revision ID: 1fa3f16860fa
Revises: 29ab2ee9af44
Create Date: 2018-04-11 16:45:21.581630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fa3f16860fa'
down_revision = '29ab2ee9af44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_environment', 'finger_print')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_environment', sa.Column('finger_print', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    # ### end Alembic commands ###
