"""empty message

Revision ID: 25d802a5f282
Revises: 6c47f87c225f
Create Date: 2018-03-26 10:59:09.657201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25d802a5f282'
down_revision = '6c47f87c225f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmarkproposal', sa.Column('email', sa.String(length=64), nullable=True))
    op.drop_constraint('webmarkproposal_ibfk_1', 'webmarkproposal', type_='foreignkey')
    op.drop_column('webmarkproposal', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmarkproposal', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('webmarkproposal_ibfk_1', 'webmarkproposal', 'users', ['author_id'], ['id'])
    op.drop_column('webmarkproposal', 'email')
    # ### end Alembic commands ###
