"""empty message

Revision ID: 27a6a545cad4
Revises: 4bba62c47891
Create Date: 2018-04-11 15:07:04.825293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27a6a545cad4'
down_revision = '4bba62c47891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_environment', sa.Column('cpu_id', sa.Integer(), nullable=True))
    op.add_column('e_environment', sa.Column('gpu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'e_environment', 'e_cpu', ['cpu_id'], ['id'])
    op.create_foreign_key(None, 'e_environment', 'e_gpu', ['gpu_id'], ['id'])
    op.drop_constraint('e_hardware_ibfk_1', 'e_hardware', type_='foreignkey')
    op.drop_constraint('e_hardware_ibfk_2', 'e_hardware', type_='foreignkey')
    op.drop_column('e_hardware', 'gpu_id')
    op.drop_column('e_hardware', 'cpu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_hardware', sa.Column('cpu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('e_hardware', sa.Column('gpu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('e_hardware_ibfk_2', 'e_hardware', 'e_gpu', ['gpu_id'], ['id'])
    op.create_foreign_key('e_hardware_ibfk_1', 'e_hardware', 'e_cpu', ['cpu_id'], ['id'])
    op.drop_constraint(None, 'e_environment', type_='foreignkey')
    op.drop_constraint(None, 'e_environment', type_='foreignkey')
    op.drop_column('e_environment', 'gpu_id')
    op.drop_column('e_environment', 'cpu_id')
    # ### end Alembic commands ###
