"""empty message

Revision ID: 28b564c8ffc4
Revises: 6536d6e30666
Create Date: 2018-04-03 10:32:18.110343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b564c8ffc4'
down_revision = '6536d6e30666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmark', sa.Column('news_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmark', 'news_count')
    # ### end Alembic commands ###
