"""empty message

Revision ID: 29ab2ee9af44
Revises: eff13ff79c51
Create Date: 2018-04-11 16:32:21.207117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29ab2ee9af44'
down_revision = 'eff13ff79c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('e_environment_ibfk_6', 'e_environment', type_='foreignkey')
    op.drop_column('e_environment', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_environment', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('e_environment_ibfk_6', 'e_environment', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
