"""empty message

Revision ID: 29de48ef05f1
Revises: 47cf5a55eb3c
Create Date: 2018-04-11 13:56:35.443192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29de48ef05f1'
down_revision = '47cf5a55eb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_hardware', 'screen_pixeldepth')
    op.drop_column('e_hardware', 'screen_available_height')
    op.drop_column('e_hardware', 'screen_colordepth')
    op.drop_column('e_hardware', 'screen_available_width')
    op.drop_column('e_hardware', 'device_pixelratio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_hardware', sa.Column('device_pixelratio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('e_hardware', sa.Column('screen_available_width', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('e_hardware', sa.Column('screen_colordepth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('e_hardware', sa.Column('screen_available_height', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('e_hardware', sa.Column('screen_pixeldepth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
