"""empty message

Revision ID: 30729691babc
Revises: 1fa3f16860fa
Create Date: 2018-04-16 09:59:36.702216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30729691babc'
down_revision = '1fa3f16860fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webmark_id', sa.Integer(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['webmark_id'], ['webmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_timestamp'), 'test', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_timestamp'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
