"""empty message

Revision ID: 37310c7a1ea6
Revises: c92cf27ea9a4
Create Date: 2018-04-11 09:28:24.311322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37310c7a1ea6'
down_revision = 'c92cf27ea9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=True))
    # ### end Alembic commands ###
