"""empty message

Revision ID: 464d7ba68d4f
Revises: 37310c7a1ea6
Create Date: 2018-04-11 10:17:58.349347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '464d7ba68d4f'
down_revision = '37310c7a1ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_browser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=16), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('engine_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_browser_timestamp'), 'e_browser', ['timestamp'], unique=False)
    op.create_table('e_cpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('cpu_architecture', sa.String(length=32), nullable=True),
    sa.Column('cpu_hardware_concurrency', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_cpu_timestamp'), 'e_cpu', ['timestamp'], unique=False)
    op.create_table('e_gpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('gpu_vender', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_gpu_timestamp'), 'e_gpu', ['timestamp'], unique=False)
    op.create_table('e_software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('os', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_software_timestamp'), 'e_software', ['timestamp'], unique=False)
    op.create_table('e_hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_id', sa.Integer(), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('device_vendor', sa.String(length=64), nullable=True),
    sa.Column('device_model', sa.String(length=32), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('screen_available_width', sa.Integer(), nullable=True),
    sa.Column('screen_available_height', sa.Integer(), nullable=True),
    sa.Column('screen_colordepth', sa.Integer(), nullable=True),
    sa.Column('screen_pixeldepth', sa.Integer(), nullable=True),
    sa.Column('device_pixelratio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cpu_id'], ['e_cpu.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['e_gpu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_hardware_timestamp'), 'e_hardware', ['timestamp'], unique=False)
    op.create_table('e_environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('browser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['browser_id'], ['e_browser.id'], ),
    sa.ForeignKeyConstraint(['hardware_id'], ['e_hardware.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['e_software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_environment_timestamp'), 'e_environment', ['timestamp'], unique=False)
    op.add_column('score', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'score', 'e_environment', ['environment_id'], ['id'])
    op.drop_column('score', 'hardware_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('hardware_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'environment_id')
    op.drop_index(op.f('ix_e_environment_timestamp'), table_name='e_environment')
    op.drop_table('e_environment')
    op.drop_index(op.f('ix_e_hardware_timestamp'), table_name='e_hardware')
    op.drop_table('e_hardware')
    op.drop_index(op.f('ix_e_software_timestamp'), table_name='e_software')
    op.drop_table('e_software')
    op.drop_index(op.f('ix_e_gpu_timestamp'), table_name='e_gpu')
    op.drop_table('e_gpu')
    op.drop_index(op.f('ix_e_cpu_timestamp'), table_name='e_cpu')
    op.drop_table('e_cpu')
    op.drop_index(op.f('ix_e_browser_timestamp'), table_name='e_browser')
    op.drop_table('e_browser')
    # ### end Alembic commands ###
