"""empty message

Revision ID: 47cf5a55eb3c
Revises: d08103da900b
Create Date: 2018-04-11 13:36:03.027085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47cf5a55eb3c'
down_revision = 'd08103da900b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_browser', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('e_browser', 'browser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_browser', sa.Column('browser', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.drop_column('e_browser', 'name')
    # ### end Alembic commands ###
