"""empty message

Revision ID: 4bba62c47891
Revises: 86f0ce2d1f74
Create Date: 2018-04-11 14:57:31.539240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bba62c47891'
down_revision = '86f0ce2d1f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_cpu', sa.Column('architecture', sa.String(length=32), nullable=True))
    op.add_column('e_cpu', sa.Column('hardware_concurrency', sa.String(length=8), nullable=True))
    op.drop_column('e_cpu', 'cpu_architecture')
    op.drop_column('e_cpu', 'cpu_hardware_concurrency')
    op.add_column('e_gpu', sa.Column('vender', sa.String(length=128), nullable=True))
    op.drop_column('e_gpu', 'gpu_vender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_gpu', sa.Column('gpu_vender', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('e_gpu', 'vender')
    op.add_column('e_cpu', sa.Column('cpu_hardware_concurrency', mysql.VARCHAR(collation='utf8_unicode_ci', length=8), nullable=True))
    op.add_column('e_cpu', sa.Column('cpu_architecture', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=True))
    op.drop_column('e_cpu', 'hardware_concurrency')
    op.drop_column('e_cpu', 'architecture')
    # ### end Alembic commands ###
