"""empty message

Revision ID: 51e238f3c811
Revises: 30729691babc
Create Date: 2018-04-16 10:14:38.917571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51e238f3c811'
down_revision = '30729691babc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('webmark', sa.Column('duration', sa.String(length=32), nullable=True))
    op.add_column('webmark', sa.Column('ready', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmark', 'ready')
    op.drop_column('webmark', 'duration')
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('webmark_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ready', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('duration', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=True),
    sa.Column('note', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='test_ibfk_1'),
    sa.ForeignKeyConstraint(['webmark_id'], ['webmark.id'], name='test_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
