"""empty message

Revision ID: 67a2c280c9ce
Revises: 9242498d1527
Create Date: 2018-04-18 10:20:48.710737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a2c280c9ce'
down_revision = '9242498d1527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webmark_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(length=64), nullable=True),
    sa.Column('device_vendor', sa.String(length=64), nullable=True),
    sa.Column('device_model', sa.String(length=32), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('device_memory', sa.String(length=8), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('cpu_name', sa.String(length=128), nullable=True),
    sa.Column('cpu_architecture', sa.String(length=32), nullable=True),
    sa.Column('cpu_hardware_concurrency', sa.String(length=8), nullable=True),
    sa.Column('gpu_name', sa.String(length=128), nullable=True),
    sa.Column('gpu_vender', sa.String(length=128), nullable=True),
    sa.Column('os', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=8), nullable=True),
    sa.Column('browser_name', sa.String(length=64), nullable=True),
    sa.Column('browser_version', sa.String(length=64), nullable=True),
    sa.Column('browser_major', sa.String(length=16), nullable=True),
    sa.Column('browser_language', sa.String(length=8), nullable=True),
    sa.Column('browser_engine_name', sa.String(length=16), nullable=True),
    sa.Column('browser_engine_version', sa.String(length=16), nullable=True),
    sa.Column('browser_ua', sa.String(length=256), nullable=True),
    sa.Column('browser_channel', sa.String(length=12), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['webmark_id'], ['webmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_timestamp'), 'scores', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_timestamp'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
