"""empty message

Revision ID: 7b6575f2bec2
Revises: 2347d15b00f7
Create Date: 2018-03-26 12:53:22.574729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6575f2bec2'
down_revision = '2347d15b00f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmarkproposal', sa.Column('added', sa.Boolean(), nullable=True))
    op.add_column('webmarkproposal', sa.Column('reviewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmarkproposal', 'reviewed')
    op.drop_column('webmarkproposal', 'added')
    # ### end Alembic commands ###
