"""empty message

Revision ID: 86f0ce2d1f74
Revises: e842c009df6e
Create Date: 2018-04-11 14:10:48.135186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f0ce2d1f74'
down_revision = 'e842c009df6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_browser', sa.Column('version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_browser', 'version')
    # ### end Alembic commands ###
