"""empty message

Revision ID: 9242498d1527
Revises: 51e238f3c811
Create Date: 2018-04-16 13:50:17.533872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9242498d1527'
down_revision = '51e238f3c811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmark', sa.Column('config', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmark', 'config')
    # ### end Alembic commands ###
