"""empty message

Revision ID: 946e6cc0f4b5
Revises: e00a306ca006
Create Date: 2018-03-30 09:30:19.662714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946e6cc0f4b5'
down_revision = 'e00a306ca006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmark', sa.Column('click_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmark', 'click_count')
    # ### end Alembic commands ###
