"""empty message

Revision ID: 9df601601e69
Revises: 67a2c280c9ce
Create Date: 2018-04-19 16:13:18.244532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df601601e69'
down_revision = '67a2c280c9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmark', sa.Column('test_path', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmark', 'test_path')
    # ### end Alembic commands ###
