"""empty message

Revision ID: b230f66d6223
Revises: 08b37f302f66
Create Date: 2018-04-11 14:03:44.571043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b230f66d6223'
down_revision = '08b37f302f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_browser', sa.Column('engine_version', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_browser', 'engine_version')
    # ### end Alembic commands ###
