"""empty message

Revision ID: c2597252f5fc
Revises: 9df601601e69
Create Date: 2018-04-20 15:32:52.509260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2597252f5fc'
down_revision = '9df601601e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmark', sa.Column('score_measurement_unit', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmark', 'score_measurement_unit')
    # ### end Alembic commands ###
