"""empty message

Revision ID: c92cf27ea9a4
Revises: aee72fb1f76c
Create Date: 2018-04-10 11:04:59.458683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92cf27ea9a4'
down_revision = 'aee72fb1f76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('global_subscribe', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'global_subscribe')
    # ### end Alembic commands ###
