"""empty message

Revision ID: d08103da900b
Revises: c56fe74c489f
Create Date: 2018-04-11 13:19:02.835282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08103da900b'
down_revision = 'c56fe74c489f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_environment', sa.Column('finger_print', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_environment', 'finger_print')
    # ### end Alembic commands ###
