"""empty message

Revision ID: e842c009df6e
Revises: b230f66d6223
Create Date: 2018-04-11 14:07:38.561918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e842c009df6e'
down_revision = 'b230f66d6223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_hardware', sa.Column('device_memory', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_hardware', 'device_memory')
    # ### end Alembic commands ###
