"""empty message

Revision ID: eff13ff79c51
Revises: 27a6a545cad4
Create Date: 2018-04-11 16:22:19.070518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff13ff79c51'
down_revision = '27a6a545cad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_environment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'e_environment', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'e_environment', type_='foreignkey')
    op.drop_column('e_environment', 'author_id')
    # ### end Alembic commands ###
