"""empty message

Revision ID: f44759dd72c3
Revises: 8bbb7221657e
Create Date: 2018-03-29 16:27:01.729067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44759dd72c3'
down_revision = '8bbb7221657e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webmark', sa.Column('rating_avg', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webmark', 'rating_avg')
    # ### end Alembic commands ###
